CREATE TABLE IF NOT EXISTS JOB  (
    JOB_ID              INTEGER     PRIMARY KEY AUTOINCREMENT   NOT NULL,
    JOB_TYPE            TEXT    NOT NULL,
    JOB_SUBTYPE         TEXT    NOT NULL,
    JOB_SUBTYPE_NAME    TEXT    NOT NULL,
    IS_RC_OR_STONE      CHAR(1) NOT NULL
);

CREATE TABLE IF NOT EXISTS EMPLOYEE (
    EMP_ID          INTEGER     PRIMARY KEY AUTOINCREMENT  NOT NULL,
    FIRST_NAME      TEXT        NOT NULL,
    LAST_NAME       TEXT        NOT NULL,
    PASSWORD        TEXT        NOT NULL,
    DOB             DATETIME    NOT NULL,
    MOBILE_NO       TEXT        UNIQUE NOT NULL,
    EMP_TYPE        TEXT        NOT NULL,
    SUB_EMP_TYPE    TEXT,
    IS_WORKING      CHAR(1),
    IS_SALARIED     CHAR(1)     NOT NULL,
    SALARY          REAL        NOT NULL,
    ADVANCE         REAL,
    JOB_ID          INTEGER     NOT NULL,

    FOREIGN KEY(JOB_ID) REFERENCES JOB(JOB_ID)
);

CREATE TABLE IF NOT EXISTS SALARY (
    EMP_ID          INTEGER     NOT NULL,
    SALARY_AMOUNT   REAL        NOT NULL,
    DATE_OF_CREDIT  DATETIME    NOT NULL,

    FOREIGN KEY(EMP_ID)     REFERENCES  EMPLOYEE(EMP_ID)
);

CREATE TABLE IF NOT EXISTS ADVANCE_SALARY (
    EMP_ID          INTEGER     NOT NULL,
    ADVANCE_AMOUNT  REAL        NOT NULL,
    ADVANCE_DATE    DATETIME    NOT NULL,

    FOREIGN KEY(EMP_ID)     REFERENCES  EMPLOYEE(EMP_ID)
);

CREATE TABLE IF NOT EXISTS MAKING_JOB (
    EMP_ID              INTEGER     NOT NULL,
    JOB_ID              INTEGER     NOT NULL,
    TOTAL_ITEMS_MADE    INTEGER     NOT NULL,
    MAKING_DATE         DATETIME    NOT NULL,
    PAID_AMOUNT         REAL        NOT NULL,

    FOREIGN KEY(EMP_ID)     REFERENCES EMPLOYEE(EMP_ID),
    FOREIGN KEY(JOB_ID)     REFERENCES JOB(JOB_ID)
)